package arcade

// Game 描述一个已注册到主程序中的小游戏。
// 每个游戏都拥有独立入口目录，可单独作为静态站点部署。
type Game struct {
	Slug            string   `json:"slug"`
	Name            string   `json:"name"`
	Tagline         string   `json:"tagline"`
	Description     string   `json:"description"`
	Category        string   `json:"category"`
	Mode            string   `json:"mode"`
	Icon            string   `json:"icon"`
	Route           string   `json:"route"`
	StandaloneEntry string   `json:"standalone_entry"`
	AuthRequired    bool     `json:"auth_required"`
	Featured        bool     `json:"featured"`
	Badges          []string `json:"badges"`
	Features        []string `json:"features"`
}

// RegisteredGames 返回当前已注册到主程序的小游戏列表。
func RegisteredGames() []Game {
	return []Game{
		{
			Slug:            "gomoku",
			Name:            "五子棋",
			Tagline:         "登录后进入专属对局，黑白对弈，五子连珠者胜。",
			Description:     "带注册、登录、会话恢复与专属对局隔离的策略对弈小游戏。",
			Category:        "策略对弈",
			Mode:            "账号玩法",
			Icon:            "●○",
			Route:           "/games/gomoku/",
			StandaloneEntry: "web/static/games/gomoku/",
			AuthRequired:    true,
			Featured:        true,
			Badges:          []string{"账号系统", "Canvas 棋盘"},
			Features:        []string{"登录 / 注册", "专属对局", "悔棋 / 重置", "落子记录"},
		},
		{
			Slug:            "linkup",
			Name:            "连连看",
			Tagline:         "相同图块在两次转弯内可连通时即可消除。",
			Description:     "纯前端休闲益智小游戏，支持洗牌、计时与步数统计。",
			Category:        "休闲益智",
			Mode:            "单机玩法",
			Icon:            "🍒",
			Route:           "/games/linkup/",
			StandaloneEntry: "web/static/games/linkup/",
			AuthRequired:    false,
			Featured:        true,
			Badges:          []string{"连线消除", "单机"},
			Features:        []string{"两次转弯连通", "重新开始", "重新洗牌", "计时 / 步数"},
		},
		{
			Slug:            "2048",
			Name:            "2048",
			Tagline:         "合并数字方块，挑战更高分数与更大数字。",
			Description:     "经典数字合成小游戏，支持键盘操作、分数统计与本地最高分。",
			Category:        "数字益智",
			Mode:            "单机玩法",
			Icon:            "2048",
			Route:           "/games/2048/",
			StandaloneEntry: "web/static/games/2048/",
			AuthRequired:    false,
			Featured:        true,
			Badges:          []string{"数字合成", "键盘操作"},
			Features:        []string{"4x4 棋盘", "方向移动", "分数统计", "最高分记录"},
		},
		{
			Slug:            "snake",
			Name:            "贪吃蛇",
			Tagline:         "控制小蛇吃到食物，不断变长并刷新最高分。",
			Description:     "经典街机小游戏，支持暂停、重新开始和本地最佳成绩记录。",
			Category:        "街机动作",
			Mode:            "单机玩法",
			Icon:            "🐍",
			Route:           "/games/snake/",
			StandaloneEntry: "web/static/games/snake/",
			AuthRequired:    false,
			Featured:        true,
			Badges:          []string{"街机", "Canvas"},
			Features:        []string{"方向控制", "暂停 / 重开", "分数统计", "逐步加速"},
		},
		{
			Slug:            "minesweeper",
			Name:            "扫雷",
			Tagline:         "标记地雷、推断安全格，清空雷区即可获胜。",
			Description:     "原生前端实现的经典扫雷，支持插旗、展开空白区域与胜负判定。",
			Category:        "策略益智",
			Mode:            "单机玩法",
			Icon:            "💣",
			Route:           "/games/minesweeper/",
			StandaloneEntry: "web/static/games/minesweeper/",
			AuthRequired:    false,
			Featured:        true,
			Badges:          []string{"逻辑推理", "经典玩法"},
			Features:        []string{"左键翻开", "右键插旗", "自动展开空白", "计时统计"},
		},
		{
			Slug:            "tetris",
			Name:            "俄罗斯方块",
			Tagline:         "旋转并堆叠方块，消行得分，随着等级提升加快下落速度。",
			Description:     "经典方块消除玩法，支持旋转、硬降、等级与分数系统。",
			Category:        "街机动作",
			Mode:            "单机玩法",
			Icon:            "🧱",
			Route:           "/games/tetris/",
			StandaloneEntry: "web/static/games/tetris/",
			AuthRequired:    false,
			Featured:        true,
			Badges:          []string{"方块消除", "Canvas"},
			Features:        []string{"旋转 / 移动", "硬降", "分数 / 等级", "消行统计"},
		},
		{
			Slug:            "tictactoe",
			Name:            "井字棋",
			Tagline:         "经典 3x3 双人对弈，率先连成一线即获胜。",
			Description:     "轻量本地双人小游戏，支持重新开始、平局判定与连续胜场统计。",
			Category:        "策略对弈",
			Mode:            "本地双人",
			Icon:            "XO",
			Route:           "/games/tictactoe/",
			StandaloneEntry: "web/static/games/tictactoe/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"双人对弈", "轻策略"},
			Features:        []string{"3x3 棋盘", "胜负判定", "平局判定", "战绩统计"},
		},
		{
			Slug:            "memory-match",
			Name:            "记忆翻牌",
			Tagline:         "翻开卡牌、记住位置，在更少步数内完成所有配对。",
			Description:     "休闲记忆小游戏，支持计时、步数统计和完成后通关反馈。",
			Category:        "记忆益智",
			Mode:            "单机玩法",
			Icon:            "🃏",
			Route:           "/games/memory-match/",
			StandaloneEntry: "web/static/games/memory-match/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"翻牌配对", "记忆训练"},
			Features:        []string{"4x4 卡牌", "翻牌配对", "步数统计", "计时通关"},
		},
		{
			Slug:            "breakout",
			Name:            "打砖块",
			Tagline:         "控制挡板反弹小球，击碎全部砖块即可过关。",
			Description:     "经典街机反弹类小游戏，支持多条命、分数统计和重开。",
			Category:        "街机动作",
			Mode:            "单机玩法",
			Icon:            "🏓",
			Route:           "/games/breakout/",
			StandaloneEntry: "web/static/games/breakout/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"反弹", "Canvas"},
			Features:        []string{"挡板控制", "砖块消除", "生命系统", "分数统计"},
		},
		{
			Slug:            "whack-a-mole",
			Name:            "打地鼠",
			Tagline:         "在倒计时内尽可能多地击中地鼠，冲击更高分。",
			Description:     "快节奏反应小游戏，支持计时、命中统计和本地最佳成绩。",
			Category:        "反应挑战",
			Mode:            "单机玩法",
			Icon:            "🐹",
			Route:           "/games/whack-a-mole/",
			StandaloneEntry: "web/static/games/whack-a-mole/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"反应速度", "点击操作"},
			Features:        []string{"倒计时", "随机刷新", "命中统计", "最高分记录"},
		},
		{
			Slug:            "plane-war",
			Name:            "飞机大战",
			Tagline:         "驾驶战机闪避敌机与子弹，在不断刷新的敌潮中挑战更高分。",
			Description:     "经典纵版射击小游戏，支持移动、射击、生命值与逐步提速。",
			Category:        "街机射击",
			Mode:            "单机玩法",
			Icon:            "✈️",
			Route:           "/games/plane-war/",
			StandaloneEntry: "web/static/games/plane-war/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"射击", "Canvas"},
			Features:        []string{"敌机刷新", "子弹碰撞", "生命系统", "分数与等级"},
		},
		{
			Slug:            "sudoku",
			Name:            "数独",
			Tagline:         "在 9x9 棋盘中填入正确数字，让每行每列和每宫都恰好包含 1 到 9。",
			Description:     "经典数字逻辑推理小游戏，支持预设题目、校验和提示。",
			Category:        "逻辑推理",
			Mode:            "单机玩法",
			Icon:            "⑨",
			Route:           "/games/sudoku/",
			StandaloneEntry: "web/static/games/sudoku/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"数字逻辑", "9x9"},
			Features:        []string{"预设谜题", "错误提示", "填数校验", "重新开局"},
		},
		{
			Slug:            "reversi",
			Name:            "黑白棋",
			Tagline:         "翻转对方棋子，争夺棋盘控制权，终局时棋子更多者获胜。",
			Description:     "本地双人黑白棋，实现合法落子、高亮可下位置与终局判定。",
			Category:        "策略对弈",
			Mode:            "本地双人",
			Icon:            "◐",
			Route:           "/games/reversi/",
			StandaloneEntry: "web/static/games/reversi/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"翻子对弈", "双人"},
			Features:        []string{"合法落子提示", "自动翻子", "跳过回合", "终局统计"},
		},
		{
			Slug:            "klotski",
			Name:            "华容道",
			Tagline:         "移动木块，为曹操让出通往出口的道路。",
			Description:     "经典滑块解谜小游戏，支持选择棋子后按方向移动并记录步数。",
			Category:        "解谜推箱",
			Mode:            "单机玩法",
			Icon:            "曹",
			Route:           "/games/klotski/",
			StandaloneEntry: "web/static/games/klotski/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"滑块解谜", "经典"},
			Features:        []string{"标准初始布局", "方向移动", "步数统计", "完成判定"},
		},
		{
			Slug:            "sokoban",
			Name:            "推箱子",
			Tagline:         "推动所有箱子到目标点，注意箱子不能穿墙也不能被拉回。",
			Description:     "基于网格地图的经典推箱子，支持重开、步数统计与胜利检测。",
			Category:        "解谜推箱",
			Mode:            "单机玩法",
			Icon:            "📦",
			Route:           "/games/sokoban/",
			StandaloneEntry: "web/static/games/sokoban/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"箱子解谜", "网格地图"},
			Features:        []string{"方向移动", "箱子推进", "目标点检测", "步数统计"},
		},
		{
			Slug:            "word-guess",
			Name:            "猜单词",
			Tagline:         "在有限次数内猜出目标单词，并根据颜色反馈逐步逼近正确答案。",
			Description:     "类似 Wordle 的猜词小游戏，支持 6 次尝试与字母命中反馈。",
			Category:        "文字益智",
			Mode:            "单机玩法",
			Icon:            "WORD",
			Route:           "/games/word-guess/",
			StandaloneEntry: "web/static/games/word-guess/",
			AuthRequired:    false,
			Featured:        false,
			Badges:          []string{"单词推理", "6次尝试"},
			Features:        []string{"字母反馈", "尝试限制", "随机词库", "重新开局"},
		},
	}
}
